parameters:

    ecentria.api.constraint.circular_reference.class: Ecentria\Libraries\EcentriaRestBundle\Validator\Constraints\CircularReferenceValidator
    ecentria.api.constraint.email.class:              Ecentria\Libraries\EcentriaRestBundle\Validator\Constraints\EmailValidator
    ecentria.api.constraint.in_array.class:           Ecentria\Libraries\EcentriaRestBundle\Validator\Constraints\InArrayValidator
    ecentria.api.constraint.unique_entity.class:      Ecentria\Libraries\EcentriaRestBundle\Validator\Constraints\UniqueEntityValidator

    ecentria.api.validator.class:                     Symfony\Component\Validator\Validator\RecursiveValidator

services:

    # Constraints
    ecentria.api.constraint.circular_reference:
        class: "%ecentria.api.constraint.circular_reference.class%"
        tags:
            - { name: validator.constraint_validator, alias: circular_reference }
        calls:
            - [ setRegistry, [ "@doctrine" ] ]

    ecentria.api.constraint.email:
        class: "%ecentria.api.constraint.email.class%"
        tags:
            - { name: validator.constraint_validator, alias: email }

    ecentria.api.constraint.in_array:
        class: "%ecentria.api.constraint.in_array.class%"
        tags:
            - { name: validator.constraint_validator, alias: in_array }

    ecentria.api.constraint.unique_entity:
        class: "%ecentria.api.constraint.unique_entity.class%"
        arguments:
            - "@doctrine"
        tags:
            - { name: validator.constraint_validator, alias: unique_entity }
        calls:
            - [ setRegistry, [ "@doctrine" ] ]

    # Validators
    ecentria.api.validator:
        class: "%ecentria.api.validator.class%"
        factory: ["@validator.builder", getValidator]